on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/segmentor-340421/segmentor:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: segmentor-340421
          service_account_email: github-actions@segmentor-340421.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cache install Nix packages
        uses: rikhuijzer/cache-install@v1.0.9
        with:
          key: nix-${{ hashFiles('cachepackages.nix') }}
          nix_file: 'cachepackages.nix'
          
      - name: Install crate2nix
        run: nix-env -i -f https://github.com/kolloch/crate2nix/tarball/master

      - name: Run crate2nix
        run: crate2nix generate

      - name: Build
        run: nix-build

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
          
      - name: Load Docker image
        run: docker load < ./result

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: gcloud run deploy segmentor-340421 --image $IMAGE_NAME --region europe-north1 --platform managed --port 8088
