on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/segmentor-340421/segmentor:latest
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: segmentor-340421
          service_account_email: github-actions@segmentor-340421.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: gcloud run deploy segmentor-340421 --image $IMAGE_NAME --region europe-north1 --platform managed --port 8088
