# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Elm
      uses: justgook/setup-elm@v1
      with:
        # Version of Elm to use. E.g. 0.19.1
        elm-version: 0.19.1

    - run: elm make src/Main.elm --output=dist/index.html --optimize
    - run: cp -r src/images dist/

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: dist
        fqdn: kom.one
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
