name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Write Strava API config file    
      run: 'echo "$SSH_KEY" > backend/strava_client_secret'
      shell: bash
      env:
        SSH_KEY: ${{secrets.STRAVA_CLIENT_SECRET}}

    - name: Setup Elm
      uses: justgook/setup-elm@v1
      with:
        elm-version: 0.19.1

    - name: Build Elm app
      run: elm make src/Main.elm --output=backend/static/dist/main.js --optimize

    - name: Setup Google Cloud Platform
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '285.0.0'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Publish app to Google App Engine
      run:
        gcloud -q app deploy backend/app.yaml --promote
