on: push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.conclusion }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'segmentor'
          image: 'gcr.io/cloudrun/segmentor:latest'
          region: europe-north1
          project_id: 'segmentor-340421'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
